### ISSUE TITLE
 flask-paranoid compatible with crawlers ?

### ISSUE THREAD

**Issue by Sebastianlecoz** [miguelgrinberg/flask-paranoid#13]
How can i make my flask app with flask-paranoid compatible with crawlers ? 

I tried to launch google light house on my app and the crawler seems to be redirected with a code 302. 

I know that the lines
```
from flask_paranoid import Paranoid

paranoid = Paranoid()

def register_extensions(app):
   paranoid.init_app(app)
   paranoid.redirect_view = '/'
   

```
are causing the issue. 

I was wondering if either 

1) there is a way to have some routes exempt from flask paranoid

or 

2) I am not using the package correctly

**Comment by miguelgrinberg** [comment]
There is no support for adding exceptions, but maybe you can actually do this if you erase the session by calling `paranoid.clear_session()` in your route or after_request handler. That will prevent the session from being set and every request will look like it is the first from that client.

**Comment by Sebastianlecoz** [comment]
Thank you. 
I'll try that.
